//
// This file was generated by the JPA Modeler
//
package tn.esprit.R2S.model;

import javax.persistence.Embeddable;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author EvilKidss
 */
@Embeddable
public class CandidateSkillPK implements Serializable {

    private Long candidate;

    private Long skill;

    public CandidateSkillPK(Long candidate, Long skill) {
        this.candidate = candidate;
        this.skill = skill;
    }

    public CandidateSkillPK() {

    }

    public Long getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Long candidate) {
        this.candidate = candidate;
    }

    public Long getSkill() {
        return this.skill;
    }

    public void setSkill(Long skill) {
        this.skill = skill;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + Objects.hashCode(this.candidate);
        hash = 59 * hash + Objects.hashCode(this.skill);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CandidateSkillPK other = (CandidateSkillPK) obj;
        if (!Objects.equals(this.candidate, other.candidate)) {
            return false;
        }
        if (!Objects.equals(this.skill, other.skill)) {
            return false;
        }
        return true;
    }

}
