/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

@Entity
public class Candidate extends Users implements Serializable {

    @OneToOne(targetEntity = CandidateSkill.class, mappedBy = "candidate")
    private CandidateSkill candidateSkill;

    @ManyToOne(targetEntity = Employee.class)
    private Employee referee;

    @OneToMany(targetEntity = Certification.class, mappedBy = "candidate")
    private List<Certification> certifications;

    @OneToMany(targetEntity = Education.class, mappedBy = "candidate")
    private List<Education> educations;

    @OneToMany(targetEntity = Experience.class, mappedBy = "candidate")
    private List<Experience> experiences;

    @OneToMany(targetEntity = CandidateJob.class, mappedBy = "candidate")
    private List<CandidateJob> jobs;

    @OneToMany(targetEntity = Interview.class, mappedBy = "candidate")
    private List<Interview> interviews;

    @OneToMany(targetEntity = CandidateQuizModel.class, mappedBy = "candidate")
    private List<CandidateQuizModel> candidateQuizModels;

    public CandidateSkill getCandidateSkill() {
        return this.candidateSkill;
    }

    public void setCandidateSkill(CandidateSkill candidateSkill) {
        this.candidateSkill = candidateSkill;
    }

    public Employee getReferee() {
        return this.referee;
    }

    public void setReferee(Employee referee) {
        this.referee = referee;
    }

    public List<Certification> getCertifications() {
        return this.certifications;
    }

    public void setCertifications(List<Certification> certifications) {
        this.certifications = certifications;
    }

    public List<Education> getEducations() {
        return this.educations;
    }

    public void setEducations(List<Education> educations) {
        this.educations = educations;
    }

    public List<Experience> getExperiences() {
        return this.experiences;
    }

    public void setExperiences(List<Experience> experiences) {
        this.experiences = experiences;
    }

    public List<CandidateJob> getJobs() {
        return this.jobs;
    }

    public void setJobs(List<CandidateJob> jobs) {
        this.jobs = jobs;
    }

    public List<Interview> getInterviews() {
        return this.interviews;
    }

    public void setInterviews(List<Interview> interviews) {
        this.interviews = interviews;
    }

    public List<CandidateQuizModel> getCandidateQuizModels() {
        return this.candidateQuizModels;
    }

    public void setCandidateQuizModels(List<CandidateQuizModel> candidateQuizModels) {
        this.candidateQuizModels = candidateQuizModels;
    }

}
