/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToOne;

@Entity
@IdClass(CandidateSkillPK.class)
public class CandidateSkill implements Serializable {


    private Integer level;

    @Id
    @OneToOne(targetEntity = Skill.class)
    private Skill skill;

    @Id
    @OneToOne(targetEntity = Candidate.class)
    private Candidate candidate;

    public Integer getLevel() {
        return this.level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Skill getSkill() {
        return this.skill;
    }

    public void setSkill(Skill skill) {
        this.skill = skill;
    }

    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

}
