/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tn.esprit.R2S.util.enums.Progress;

@Entity
@IdClass(CandidateJobPK.class)
public class CandidateJob implements Serializable {

    @Enumerated
    private Progress progress;

    @Temporal(TemporalType.TIMESTAMP)
    private Date date;

    @Id
    @ManyToOne(targetEntity = Job.class)
    private Job job;

    @Id
    @ManyToOne(targetEntity = Candidate.class)
    private Candidate candidate;

    public Progress getProgress() {
        return this.progress;
    }

    public void setProgress(Progress progress) {
        this.progress = progress;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Job getJob() {
        return this.job;
    }

    public void setJob(Job job) {
        this.job = job;
    }

    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

}
