/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * @author Ouerghi Yassine
 */
@Entity
public class CandidateAnswer implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(targetEntity = CandidateQuizModel.class)
    private CandidateQuizModel candidateQuizModel;

    @OneToMany(targetEntity = Question.class, mappedBy = "candidateAnswer")
    private List<Question> questions;

    @OneToMany(targetEntity = Answer.class, mappedBy = "candidateAnswer")
    private List<Answer> answers;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CandidateQuizModel getCandidateQuizModel() {
        return this.candidateQuizModel;
    }

    public void setCandidateQuizModel(CandidateQuizModel candidateQuizModel) {
        this.candidateQuizModel = candidateQuizModel;
    }

    public List<Question> getQuestions() {
        return this.questions;
    }

    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }

    public List<Answer> getAnswers() {
        return this.answers;
    }

    public void setAnswers(List<Answer> answers) {
        this.answers = answers;
    }

}
