/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import javax.persistence.Entity;
import java.io.Serializable;

/**
 * @author EvilKidss
 */
@Entity
public class ChiefHumanResourcesOfficer extends Users implements Serializable {

}
