/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlTransient;
import java.io.Serializable;
import java.util.List;

/**
 * @author EvilKids
 */
@Entity
public class Employee extends Users implements Serializable {


    private Integer credibility;

    @OneToMany(targetEntity = Candidate.class, mappedBy = "referee")

    private List<Candidate> referredCandidates;

    public Integer getCredibility() {
        return this.credibility;
    }

    public void setCredibility(Integer credibility) {
        this.credibility = credibility;
    }

    @XmlTransient
    public List<Candidate> getReferredCandidates() {
        return this.referredCandidates;
    }

    public void setReferredCandidates(List<Candidate> referredCandidates) {
        this.referredCandidates = referredCandidates;
    }

}
