/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonRootName;
import tn.esprit.R2S.util.enums.JobStatus;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author EvilKids
 */
@Entity
@JsonRootName("job")
@JsonIgnoreProperties(value = {"quizModel", "rewards", "skills", "candidates", "jobFieldValues"})
public class Job implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String description;

    private Double salary;


    @Enumerated
    private JobStatus status;

    @ManyToMany(targetEntity = QuizModel.class)
    private List<QuizModel> quizModel;

    @OneToMany(targetEntity = Reward.class, mappedBy = "job")
    private List<Reward> rewards;

    @OneToMany(targetEntity = CandidateJob.class, mappedBy = "job")
    private List<CandidateJob> candidates;

    @ManyToMany(targetEntity = Skill.class, mappedBy = "jobs", cascade = CascadeType.ALL)
    private List<Skill> skills;

    @OneToMany(targetEntity = JobFieldValue.class, mappedBy = "jobField")
    private List<JobFieldValue> jobFieldValues;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public JobStatus getStatus() {
        return this.status;
    }

    public void setStatus(JobStatus status) {
        this.status = status;
    }

    public List<QuizModel> getQuizModel() {
        return this.quizModel;
    }

    public void setQuizModel(List<QuizModel> quizModel) {
        this.quizModel = quizModel;
    }

    public List<Reward> getRewards() {
        return this.rewards;
    }

    public void setRewards(List<Reward> rewards) {
        this.rewards = rewards;
    }

    public List<CandidateJob> getCandidates() {
        return this.candidates;
    }

    public void setCandidates(List<CandidateJob> candidates) {
        this.candidates = candidates;
    }

    public List<Skill> getSkills() {
        return this.skills;
    }

    public void setSkills(List<Skill> skills) {
        this.skills = skills;
    }

    public List<JobFieldValue> getJobFieldValues() {
        return jobFieldValues;
    }

    public void setJobFieldValues(List<JobFieldValue> jobFieldValues) {
        this.jobFieldValues = jobFieldValues;
    }

    @Override
    public String toString() {
        return "Job{" +
                "name='" + name + '\'' +
                '}';
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Job job = (Job) o;

        return id.equals(job.id);

    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }
}
