/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import tn.esprit.R2S.util.enums.QuestionType;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author EvilKidss
 */
@Entity
public class Question implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    private String question;

    @Enumerated
    private QuestionType type;


    private Double score;

    @ManyToOne(targetEntity = CandidateAnswer.class)
    private CandidateAnswer candidateAnswer;

    @OneToMany(targetEntity = Answer.class, mappedBy = "question")
    private List<Answer> answers;

    @ManyToMany(targetEntity = QuizModel.class)
    private List<QuizModel> quizModels;

    @ManyToOne(targetEntity = Category.class)
    private Category category;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public QuestionType getType() {
        return this.type;
    }

    public void setType(QuestionType type) {
        this.type = type;
    }

    public Double getScore() {
        return this.score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    public CandidateAnswer getCandidateAnswer() {
        return this.candidateAnswer;
    }

    public void setCandidateAnswer(CandidateAnswer candidateAnswer) {
        this.candidateAnswer = candidateAnswer;
    }

    public List<Answer> getAnswers() {
        return this.answers;
    }

    public void setAnswers(List<Answer> answers) {
        this.answers = answers;
    }

    public List<QuizModel> getQuizModels() {
        return this.quizModels;
    }

    public void setQuizModels(List<QuizModel> quizModels) {
        this.quizModels = quizModels;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Question)) return false;

        Question question = (Question) o;

        return id.equals(question.id);

    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }
}
