/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.R2S.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import tn.esprit.R2S.util.enums.Gender;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * @author EvilKids
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "user_role", discriminatorType = DiscriminatorType.STRING)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "role")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Employee.class, name = "Employee"),
        @JsonSubTypes.Type(value = Candidate.class, name = "Candidate"),
        @JsonSubTypes.Type(value = RecruitmentManager.class, name = "RecruitmentManager"),
        @JsonSubTypes.Type(value = ChiefHumanResourcesOfficer.class, name = "ChiefHumanResourcesOfficer")
})
public abstract class Users implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long cin;

    private String firstname;

    private String lastname;

    @Temporal(TemporalType.DATE)
    private Date birthday;

    private String username;

    private String password;

    private String email;

    private String tel;

    @Enumerated
    private Gender gender;

    @Embedded
    private Address address;

    public Long getCin() {
        return this.cin;
    }

    public void setCin(Long cin) {
        this.cin = cin;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

}
