/**
 * This file was generated by the JPA Modeler
 */
package tn.esprit.hrsmart.model;

import java.io.Serializable;
import javax.persistence.Entity;

/**
 * @author Ouerghi Yassine
 */
@Entity
public class ChiefHumanResourcesOfficer extends Users implements Serializable {

}
